// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHcaO3Mm_PcoAGgWZI355lwXLY9wb-NLU',
    appId: '1:161450648034:web:3729e51d5b4b95ec5719bb',
    messagingSenderId: '161450648034',
    projectId: 'social-sw1',
    authDomain: 'social-sw1.firebaseapp.com',
    storageBucket: 'social-sw1.firebasestorage.app',
    measurementId: 'G-C26DNYBV6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8tudABTJ0WeyAh67tRKmyDhCxbjmMVOY',
    appId: '1:161450648034:android:e8d7b9b5d3a504e25719bb',
    messagingSenderId: '161450648034',
    projectId: 'social-sw1',
    storageBucket: 'social-sw1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjUHgtTUFoYmbOX5JOP0W304K6x43q5dE',
    appId: '1:161450648034:ios:6d64d9a69e40624e5719bb',
    messagingSenderId: '161450648034',
    projectId: 'social-sw1',
    storageBucket: 'social-sw1.firebasestorage.app',
    iosBundleId: 'com.example.socialAppSw1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjUHgtTUFoYmbOX5JOP0W304K6x43q5dE',
    appId: '1:161450648034:ios:6d64d9a69e40624e5719bb',
    messagingSenderId: '161450648034',
    projectId: 'social-sw1',
    storageBucket: 'social-sw1.firebasestorage.app',
    iosBundleId: 'com.example.socialAppSw1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHcaO3Mm_PcoAGgWZI355lwXLY9wb-NLU',
    appId: '1:161450648034:web:b54bdf6bc3d90c765719bb',
    messagingSenderId: '161450648034',
    projectId: 'social-sw1',
    authDomain: 'social-sw1.firebaseapp.com',
    storageBucket: 'social-sw1.firebasestorage.app',
    measurementId: 'G-G0GJNHTVBP',
  );
}
